### ISSUE TITLE
`CeleryKubernetesExecutor` jobs are not queued.

### ISSUE THREAD

**Issue by jensgrnb** [airflow-helm/charts#293] opened 2021-07-09 10:23 UTC
**What is your question?**

I'm trying to get the `CeleryKubernetesExecutor` up and running on our airflow cluster. I'm upgrading from a `CeleryExecutor` where the jobs are running fine, but when I simply upgrade the executor without adding anything, no jobs are queued at all. 

task instance details gives me

![image](https://user-images.githubusercontent.com/77628274/125063841-4156b700-e0b0-11eb-8388-47d4e667acaf.png)

(the dependencies error is present when I only use `CeleryExecutor` as well, but that doesn't stop the jobs from running fine.)
the queue id for this job is `default` and I was exepecting that this upgrade of executor would not affect anything at all, but instead everything grinds to a halt. 

Anyone experiencing similar issues? I'm on latest helm chart 8.4.0 and latest airflow 2-1-1-python3.8. 

I've looked around for error logs on both the scheduler side and the worker side, but there's just nothing.

**Comment by thesuperzapper** [comment] 2021-07-12 06:20
@jensgrnb this issue is caused by airflow `2.1.1`, not the chart.

This https://github.com/apache/airflow/pull/16700, has addressed the issue, and will be included in airflow `2.1.2`.

**Comment by jensgrnb** [comment] 2021-07-12 07:19
Okay thanks for the reference! I'll be waiting eagerly for 2.1.2 then) Dodging meetings etc.

**Closed** 2021-08-19 00:45 UTC
Labels: question
