### ISSUE TITLE
Google Authentication is failing [Airflow: 2.0.2, Chart: 8.2.0]

### ISSUE THREAD

**Issue by klalafaryan** [airflow-helm/charts#223] opened 2021-06-16 08:45 UTC
**What is the bug?**

Google authentication is failing whenever we have more than two web pods configured. (`web replicas: 2`) It works perfectly fine with one pod.

<img width="1336" alt="Screenshot 2021-06-16 at 12 40 23" src="https://user-images.githubusercontent.com/1593802/122188152-bc0d2780-cea0-11eb-9a7e-a05ef01291f4.png">

**What are your Helm values?**
```
  extraPipPackages:
  #  ## the following configs require Authlib
    - "Authlib~=0.15.4"
    - "apache-airflow[google_auth,jdbc,kubernetes,postgres,s3,ssh,databricks]==2.0.2"
```

**What is your Kubernetes Version?**:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T07:38:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by thesuperzapper** [comment] 2021-06-23 01:20
@klalafaryan this is a duplicate of https://github.com/airflow-helm/charts/issues/72, please discuss there.

**Closed by thesuperzapper** 2021-06-23 01:20 UTC
Labels: bug
