### ISSUE TITLE
PYTHONPATH environment variable not being set via airflow.extraEnv

### ISSUE THREAD

**Issue by Yinabled** [airflow-helm/charts#106] opened 2021-03-27 17:18 UTC
**What is the bug?**

The `PYTHONPATH` environment variable is not being set in the Airflow environment when specified via the `airflow.extraEnv` value. Specifically, the `airflow` property values to merge with `values.yaml` are documented below.

Note that the `TESTINGVAR` variable is set properly. I confirmed by `kubectl exec`ing into `airflow-web` and printing the sourced values for both `PYTHONPATH` and `TESTINGVAR` - `TESTINGVAR` was correct whereas `PYTHONPATH` remained the default value (i.e. `/opt/python/site-packages`). 

For context, we're trying to extend our `PYTHONPATH` with the repo directory in order to import custom modules into our DAGs. (If you have any suggestions of better ways to do this as well, I'm all ears.) Any idea what might be happening here?

**What are your Helm values?**

```yaml
airflow:
  config:
    AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
  extraEnv:
    - 
      name: PYTHONPATH
      value: "/opt/python/site-packages:/opt/airflow/dags/repo"
    -
      name: TESTINGVAR
      value: "hello123"
  extraPipPackages:
    - "apache-airflow[google]==2.0.1"
    - "SQLAlchemy==1.3.23"
```

**What is your Kubernetes Version?**:

```console
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.7800", GitCommit:"cef3156c566a1d1a4b23ee360a760f45bfbaaac1", GitTreeState:"clean", BuildDate:"2020-12-14T09:12:37Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"dirty", GoVersion:"go1.15.3"}
```

**Comment by thesuperzapper** [comment] 2021-03-28 01:53
@Yinabled can you confirm if this is fixed in `8.0.2`, as PR https://github.com/airflow-helm/charts/pull/108 should have fixed it!

**Comment by Yinabled** [comment] 2021-03-28 20:32
@thesuperzapper No, this did not resolve the issue - specifically, I'm trying to extend `PYTHONPATH` with the repo directory, i.e. `/opt/airflow/dags/repo`. It looks like #108 is trying to just set `PYTHONPATH` to `/opt/python/site-packages`, which was already happening correctly before this release.

**Comment by thesuperzapper** [comment] 2021-03-28 20:37
So what was `PYTHONPATH` set to when you use `airflow.extraEnv` with version `8.0.2`?

Because it worked for me?

NOTE: the issue was that the chart's hard-coded `PYTHONPATH` was taking presidence over the user-provided `airfkow.extraEnv`.

**Comment by Yinabled** [comment] 2021-03-28 20:51
This is what I did:
1. Set the merged `values.yaml` to the following:
```
airflow:
  config:
    AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
  extraEnv:
    - 
      name: PYTHONPATH
      value: "/opt/python/site-packages:/opt/airflow/dags/repo"
  extraPipPackages:
    - "apache-airflow[google]==2.0.1"
    - "SQLAlchemy==1.3.23"
```
2. Observe that `PYTHONPATH` is still set to `/opt/python/site-packages`, and not to `/opt/python/site-packages:/opt/airflow/dags/repo` as is expected.

**Comment by Yinabled** [comment] 2021-03-28 21:34
(FYI @thesuperzapper I don't have permission to reopen closed issues)

**Comment by ms32035** [comment] 2021-03-29 20:25
Also having issues with import errors from `/opt/airflow/dags/repo`  when parsing or executing dags. didn't dig too deep why this is happening, but variables look correct when executing shell

**Comment by sk1tter** [comment] 2021-03-30 09:11
I think the problem is Airflow 2.0 serializing DAGs on `db upgrade`. Because `PYTHONPATH` is not set when running `db upgrade` serialized dags are not inserted to db and are showing errors but variables will look correct on shell.

**Comment by sk1tter** [comment] 2021-03-31 03:03
With further investigation, my previous comment was wrong. `PYTHONPATH` is being set correctly in the `db upgrade` container. I managed to fix import errors by adding an git sync init container on the web server and scheduler.
```yaml
initContainers:
    {{- if .Values.dags.gitSync.enabled }}
    {{- include "airflow.container.git_sync_init" (dict "Values" .Values "sync_one_time" "true") | indent 8 }}
    {{- end }}
```
 Hope this helps.

**Comment by ms32035** [comment] 2021-03-31 13:08
I am starting to suspect that something is wrong / lost in here:
```
          command:
            - "/usr/bin/dumb-init"
            - "--"
          args:
            - "bash"
            - "-c"
            - "exec airflow scheduler -n {{ .Values.scheduler.numRuns }}"
          {{- if .Values.scheduler.livenessProbe.enabled }}
```
all the variables are correct inside the container, when I start the scheduler manually in another container all works good, and the scheduler from deployment keeps getting import errors from the dags folder. even setting PYTHONPATH in the docker image did not help

**Comment by justincmoy** [comment] 2021-03-31 20:54
@Yinabled and I started talking about this in https://github.com/airflow-helm/charts/pull/118. Here's the context:

> Curious - would this be a means of addressing the case presented in #106? (i.e. adding the DAG directory to PYTHONPATH so as to include custom modules when syncing DAGs via git-sync)

> It didn't for me. I still needed to add the following to the top of our DAGs:
> 
> import importlib
import site
importlib.reload(site)
importlib.invalidate_caches()

> Did adding these lines in addition to the PYTHONPATH env var resolve the issue, or was setting PYTHONPATH in git-sync not necessary?

I didn't change the PYTHONPATH in git-sync. So here's our use case: we have DAGs synced from Git that define their requirements using [Poetry](https://python-poetry.org/). By using a custom git-sync image (one with Poetry installed), we can use `GIT_SYNC_HOOK_COMMAND` (hence my original PR https://github.com/airflow-helm/charts/pull/100) to run a script in the synced repo that installs Python packages to the shared volume mount.

Our DAGs use Python dependencies both within the synced repo and from Poetry and I've found I need to add both the DAGs directory and the Poetry directory to the PYTHONPATH and reload the site from the context above.

FWIW: I don't think the DAGs directory needs to be added for the web server or the scheduler, but I found it was needed for the KubernetesExecutor pods. I haven't gotten a chance to put more debugging into this, but adding the DAGs directory works.

**Comment by ms32035** [comment] 2021-04-01 09:07
Adding an init git sync container to webserver and workers fully fixes the issue. My guess as to why this started to happen is that previously there was a wait for db script, which has now been moved to an init container

**Comment by thesuperzapper** [comment] 2021-04-01 10:56
I will make a release which allows python package in your git-repo, after I try a few options (in the next day or two).

**Comment by Yinabled** [comment] 2021-04-02 18:16
Amazing - thanks so much, @thesuperzapper!

**Comment by thesuperzapper** [comment] 2021-04-09 14:04
As the actual issue raised here has been fixed in PR https://github.com/airflow-helm/charts/pull/108, lets continue to discuss the race-condition of git-sync in https://github.com/airflow-helm/charts/issues/124

**Closed by thesuperzapper** 2021-04-09 14:04 UTC
Labels: bug
